<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

class Company extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'logo',

    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($company){
            if (Storage::disk('logo')->exists($company->logo)){
                Storage::disk('logo')->delete($company->logo);
            }


        });


    }


    public function allReceipint(){
        return $this->hasMany(receipts::class,'company_id','id');
    }
}
